import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <h2>Logo</h2>
          <nav>
            <ul>
              <li>
                <Link href="/home">Home</Link>
              </li>
              <li>
                <Link href="/produto">Produto</Link>
              </li>
              <li>
                <Link href="/">Pagina inicial</Link>
              </li>
              {/* criar link do loguin */}
              <li>
                <Link href="/login">Login</Link>
              </li>
            </ul>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}

//  esse children é o conteudo que vai ser renderizado dentro do layout

// leyout é o que vai ser renderizado em todas as paginas
